# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer la nas opções de pipeline]
name: 'Execução Manual'
  # triggers OU gatilhos de execução
  # gatilho de execução manual = workflow_dispatch
on:
    workflow_dispatch:

jobs:
  # descrição do job da tarefa
    e2e-tests:
      # máquina que o job vai executar
        runs-on: ubuntu-latest
        # passo a passo das ações do job
        steps:
          - uses: actions/checkout@v4
          #  - uses: actions/chesetup-node@v4 
          #     with:
          #          node-version: lts/*
          - name: Instalando Yarn
            run: npm install -g yarn

          - name: Instalando as dependências
            run: yarn playwright install

          - name: Instalando Playwright
            run: yarn  

          - name: Teste E2E (end-to-end)
            run: yarn run e2e

            #passed,failed, cancelled
          - uses: actions/upload-artifact@v4
              11'tvrif: ${{ !cancelled() }} # Only when test failed or cancelledfailure()
              name: relatorio-de-testes
              path: ./playwright-report

