
name: 'Execução Agendada'

on:
    on:
        schedule:
           - cron: '20 19 * * 6'
            uses: szenius/set-timezone@v2.0
    with:
      timezoneLinux: "America/Sao_Paulo"
      timezoneMacOS: "America/Sao_Paulo"
      timezoneWindows: "America/Sao_Paulo"
      timezone: "America/Sao_Paulo"
jobs:
    e2e-tests:
        runs-on: ubuntu-latest            
        steps:
          - uses: actions/checkout@v4
       #  - uses: actions/chesetup-node@v4
      #     with:
      #          node-version: lts/*
          - name: Instalando Yarn
            run: npm install -g yarn
          - name: Instalando as dependências
            run: yarn
          - name: Teste E2E 
            run: yarn run e2e
            #passed,failed, cancelled
          - uses: actions/upload-artifact@v4
            if: ${{ !cancelled() }} # Only when test failed or cancelledfailure()
            with:
                  name: relatorio-de-testes
                  path: ./playwright-report
